package com.udea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContratoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoAllPropertiesEquals(Contrato expected, Contrato actual) {
        assertContratoAutoGeneratedPropertiesEquals(expected, actual);
        assertContratoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoAllUpdatablePropertiesEquals(Contrato expected, Contrato actual) {
        assertContratoUpdatableFieldsEquals(expected, actual);
        assertContratoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoAutoGeneratedPropertiesEquals(Contrato expected, Contrato actual) {
        assertThat(expected)
            .as("Verify Contrato auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoUpdatableFieldsEquals(Contrato expected, Contrato actual) {
        assertThat(expected)
            .as("Verify Contrato relevant properties")
            .satisfies(e -> assertThat(e.getFechaInicio()).as("check fechaInicio").isEqualTo(actual.getFechaInicio()))
            .satisfies(e -> assertThat(e.getFechaFin()).as("check fechaFin").isEqualTo(actual.getFechaFin()))
            .satisfies(e -> assertThat(e.getLenguaje()).as("check lenguaje").isEqualTo(actual.getLenguaje()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoUpdatableRelationshipsEquals(Contrato expected, Contrato actual) {
        assertThat(expected)
            .as("Verify Contrato relationships")
            .satisfies(e -> assertThat(e.getTrabajo()).as("check trabajo").isEqualTo(actual.getTrabajo()))
            .satisfies(e -> assertThat(e.getDepartamento()).as("check departamento").isEqualTo(actual.getDepartamento()))
            .satisfies(e -> assertThat(e.getEmpleado()).as("check empleado").isEqualTo(actual.getEmpleado()));
    }
}
