package com.udea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TareaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTareaAllPropertiesEquals(Tarea expected, Tarea actual) {
        assertTareaAutoGeneratedPropertiesEquals(expected, actual);
        assertTareaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTareaAllUpdatablePropertiesEquals(Tarea expected, Tarea actual) {
        assertTareaUpdatableFieldsEquals(expected, actual);
        assertTareaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTareaAutoGeneratedPropertiesEquals(Tarea expected, Tarea actual) {
        assertThat(expected)
            .as("Verify Tarea auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTareaUpdatableFieldsEquals(Tarea expected, Tarea actual) {
        assertThat(expected)
            .as("Verify Tarea relevant properties")
            .satisfies(e -> assertThat(e.getTitulo()).as("check titulo").isEqualTo(actual.getTitulo()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTareaUpdatableRelationshipsEquals(Tarea expected, Tarea actual) {
        assertThat(expected)
            .as("Verify Tarea relationships")
            .satisfies(e -> assertThat(e.getTrabajos()).as("check trabajos").isEqualTo(actual.getTrabajos()));
    }
}
