package com.udea.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrabajoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajoAllPropertiesEquals(Trabajo expected, Trabajo actual) {
        assertTrabajoAutoGeneratedPropertiesEquals(expected, actual);
        assertTrabajoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajoAllUpdatablePropertiesEquals(Trabajo expected, Trabajo actual) {
        assertTrabajoUpdatableFieldsEquals(expected, actual);
        assertTrabajoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajoAutoGeneratedPropertiesEquals(Trabajo expected, Trabajo actual) {
        assertThat(expected)
            .as("Verify Trabajo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajoUpdatableFieldsEquals(Trabajo expected, Trabajo actual) {
        assertThat(expected)
            .as("Verify Trabajo relevant properties")
            .satisfies(e -> assertThat(e.getTituloTrabajo()).as("check tituloTrabajo").isEqualTo(actual.getTituloTrabajo()))
            .satisfies(e -> assertThat(e.getSalarioMin()).as("check salarioMin").isEqualTo(actual.getSalarioMin()))
            .satisfies(e -> assertThat(e.getSalarioMax()).as("check salarioMax").isEqualTo(actual.getSalarioMax()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrabajoUpdatableRelationshipsEquals(Trabajo expected, Trabajo actual) {
        assertThat(expected)
            .as("Verify Trabajo relationships")
            .satisfies(e -> assertThat(e.getTareas()).as("check tareas").isEqualTo(actual.getTareas()))
            .satisfies(e -> assertThat(e.getEmpleado()).as("check empleado").isEqualTo(actual.getEmpleado()));
    }
}
